### ISSUE TITLE
After upgrading to #107 Dashboard does not refresh automatically

### ISSUE THREAD

**Issue by sm0tsc** [LX3JL/xlxd#108]
$PageOptions['PageRefreshActive']                    = true;   			// Activate automatic refresh

Is set to true

//Johan - SM0TSC

**Comment by LX1IQ** [comment]
Hi Johan,
Are you sure? I tested with edge and firefox without problems.

73, Luc

**Comment by sm0tsc** [comment]
I am using Chrome.. Will try edge...
//Johan - SM0TSC

**Comment by LX1IQ** [comment]
Just works fine at me with chrome too.
Hmm, can you check https://xlx270.epf.lu  ?

**Comment by sm0tsc** [comment]
It does not update in any browers..

I will keep monitor your XLX

Can you check http://xlx.brandmeister.se

//Johan - SM0TSC

**Comment by LX1IQ** [comment]
I see.
Try to put some text into the config.inc.php 
$PageOptions['CustomTXT']                            = 'test';					// custom text in your header

**Comment by sm0tsc** [comment]
Done
//Johan - SM0TSC

**Comment by LX1IQ** [comment]
your jquery is not loading correctly !
replace the jquery-1.12.4.min.js in your "js" folder without editing it.
________________________________________________________________________________________

HTML1300: Navigation occurred.    xlx.brandmeister.se (1,1)
HTML1420: Unexpected quote after "PUBLIC" or "SYSTEM" keyword. Expected whitespace.
xlx.brandmeister.se (1,22)

SCRIPT1002: SCRIPT1002: Syntax error   jquery-1.12.4.min.js (7,1)
0: '$' is not defined  xlx.brandmeister.se (20,9)

**Comment by sm0tsc** [comment]
Ok done...

//Johan - SM0TSC

**Comment by LX1IQ** [comment]
seems to be ok for now.

**Comment by sm0tsc** [comment]
Now seems to update.. Also Server uptimes reload correctly.. Thank you...

**Comment by LX1IQ** [comment]
you're welcome and please close the issue.
