### ISSUE TITLE
Changing the config.inc.php report to true; does nothing

### ISSUE THREAD

**Issue by 5b4amd** [LX3JL/xlxd#109]
Hi all,
i just updated my XLX146 server .After some testing that i've done locally, at my home network, i am trying now to change the reporting to true; and add the new dashboard address(instead the private IP i had for testing) but it does not seem to work?!No change to the Reflector list, any ideas please? The reflectors works ok (xlx146.ddns.net). 

73 de 5B4AMD

**Comment by LX1IQ** [comment]
Hi,
Well looks good for me ?

73, Luc

**Comment by 5b4amd** [comment]
Hi Luc!
yes ,it works now!i don't know why though. 

Thanks for your interest!
73 de 5B4AMD
George
