### ISSUE TITLE
Stream close frames are reflected back to sender

### ISSUE THREAD

**Issue by nonoo** [LX3JL/xlxd#123]
The stream is closed right after a close frame is received and this unsets the associated source station of the stream. Right after the close the close frame is sent to all stations which are subscribed to the stream, including the source station, so it receives it's own frame.

**Comment by sp2ong** [comment]
I confirm this problem and still exist in latest version xlxd

**Comment by K2IE** [comment]
What would the appropriate fix be?  Would it be to not send the close frame to the source but to the other subscribed stations?

**Comment by nonoo** [comment]
Yes

--
Norbert Varga
http://www.nonoo.hu/

**Comment by yo2loj** [comment]
The appropriate fix would be not to send ANY frame back to the source.

**Comment by K2IE** [comment]
@yo2loj could I please trouble you to propose a fix that will work witht the current codebase?  I would be willing to give it a try on my reflector.

**Comment by N5QM** [comment]
Guys is there any additional feedback or available workarounds for this issue?

**Comment by LX1IQ** [comment]
Hi,

We are trying to publish a fix probably end of the year.
73, Luc

**Comment by N5QM** [comment]
Thank you Luc, if you need any testers, please let me know and I will do my best to help out.

**Comment by LX1IQ** [comment]
fixed in v2.4.1

73, Luc
