### ISSUE TITLE
KC4 Address Not from Antartica

### ISSUE THREAD

**Issue by happyblues** [LX3JL/xlxd#130]
A user from the United States with a callsign beginning with KC4 connected and is showing to be from Antartica. According to this Wikipedia page, calls with the suffix beginning with "A" or "U" are assigned to Antartica. https://en.wikipedia.org/wiki/Amateur_radio_call_signs

**Comment by phl0** [comment]
I did a quick patch that should fix this issue.
@happyblues Could you test this pls?

**Comment by LX1IQ** [comment]
Should be ok for now.

**Comment by happyblues** [comment]
Thanks. I haven't had a chance to test. Hopefully I can tonight.

**Comment by happyblues** [comment]
Tested last night and it worked. Thanks.
