### ISSUE TITLE
YSFS ( Server status ) is missing in the YSF protocol

### ISSUE THREAD

**Issue by pa7lim** [LX3JL/xlxd#136]
Can you please implement the YSFS ( Server status ) option in the YSF protocol?

**Comment by iw2gob** [comment]
Hi, for this reason all the Openspot2/sharkrf are not able to connect to XLX in YSF mode. We hope that Luc will implement it soon. Thanks. 73, Maurizio IW2GOB

**Comment by LX1IQ** [comment]
Hi, 
YSFS is on our roadmap. Jean-Luc will probably implement it in the next XLX release.
73, Luc
