### ISSUE TITLE
Lost Hash

### ISSUE THREAD

**Issue by citynetcomputing** [LX3JL/xlxd#143]
Good Morning,

Is there somewhere to reset the has file online? I installed xlxd on a separate server (xlx892) using and old hash then updated the folder and lost it. Not it shows down. Is this possible to get it reset?

I know i should have backed it up lol

Thanks!!

**Comment by LX1IQ** [comment]
The XLXAPI server has a selfcare db.
Your old hash will be wiped frome the list after 48h downtime.

73, Luc
