### ISSUE TITLE
No telemetry info on YSF

### ISSUE THREAD

**Issue by xe1dvi** [LX3JL/xlxd#152]
Hello,
I have a YSF repeater running on pi-star, if the repeater in connected to my YSF reflector telemetry passes thru and I can see the call sign and distance of stations on the other end as they can see mine.

When I connect the repeater to my XLX077 reflector I can only see  the call sign but not distance, telemetry is not passing thru.

I have the latest 2.3.5, maybe there is a setting that I need to activate, please advice.

Thank you.

**Comment by vk4tux** [comment]
That is normal. XLX YSF connect is converted to DMR, then back to YSF 
for any other YSF client such that no GPS data is shared, as there is no 
YSF throughput.

There is nothing you can do about it.

Best to stay with YSFReflector, and use YSF2DMR back to XLX.

**Comment by xe1dvi** [comment]
Ahhhhh good to know!!!
Yeah thats how I have it linked!
Thanks Adrian.

Sincerely,
Rey.XE1DVI / W6DVI



 

    On Thursday, February 13, 2020, 10:16:18 AM PST, Adrian Fewster <notifications@github.com> wrote:  
 
 That is normal. XLX YSF connect is converted to DMR, then back to YSF 
for any other YSF client such that no GPS data is shared, as there is no 
YSF throughput.

There is nothing you can do about it.

Best to stay with YSFReflector, and use YSF2DMR back to XLX.
