### ISSUE TITLE
xlxd crashes when stream with sid 0 opens

### ISSUE THREAD

**Issue by remcovz** [LX3JL/xlxd#30]
Sometimes a client opens a stream on the xlxd server with sid 0. This triggers a networkloop with connected ircddbgateway clients. Every client re-transmits this packet and the xlxd server gets "bombarded" with streams. However I think this is actually a bug in ircddbgateway it affects xlxd as well. xlxd crashes within a second after this "loop" starts.

Log entries for clarification: 

Apr 10 12:49:32 colo xlxd: Opening stream on module B for client PD4RS   E with sid 0
Apr 10 12:49:32 colo xlxd: Detected stream loop on module B for client PA3CQJ  C with sid 0
Apr 10 12:49:32 colo xlxd: Detected stream loop on module B for client PA3CQJ  C with sid 0
Apr 10 12:49:32 colo xlxd: Detected stream loop on module B for client PA3CQJ  C with sid 0
[ .. skip ahead 1000 similar lines ]
Apr 10 12:49:32 colo xlxd: Detected stream loop on module B for client PD4FMJ  C with sid 0
Apr 10 12:49:32 colo xlxd: Detected stream loop on module B for client PD4FMJ  C with sid 0
Apr 10 12:49:32 colo xlxd: Closing stream of module B

and this is the moment it crashes. The process ends and everyone gets disconnected (about 40 clients). This crash doesn't occur always. Maybe a minimum amount of clients needs to be online to be this destructive.

Is it possible to build in a "safeguard" that drops/discards streams with sid 0? sid 0 seems to be a faulty stream id anyway so I suggest ignoring and discarding those streams. It will help a lot.

Regards,

Remco / PA4TW

**Comment by LX3JL** [comment]
Solved in 1.4.3.
xlxd ignore streams with SID=0
