### ISSUE TITLE
Info about timeout rpt/hotspot connection 

### ISSUE THREAD

**Issue by iw9grl** [LX3JL/xlxd#32]
Hi
I'm sysop of xlx090, it is installed in a vps in a computer farm with Debian OS. I noticed a strange issue, some repeaters  without any apparently problem, during a qso is disconnected from xlx and reconnected after few seconds, I ask if there is some parameters to set to avoid this issue. 
Thank you 
73 de IW9GRL

**Comment by LX1IQ** [comment]
Hi, 
What protocol are we talking about?

73,  Luc
