### ISSUE TITLE
XLX 2.0

### ISSUE THREAD

**Issue by iz7jwr** [LX3JL/xlxd#40]
Hi Luc, I am xlx332 and xlx023 's sysop. 
I have compiled and installed the new version of xlx, but the "start service" command does not start. Xlx023 is installed on a datacenter and is currently down.
73 de IZ7JWR Enrico.

**Comment by iz7jwr** [comment]
All right, after editing the arguments in /init.d/xlxd. Current version XLX023 2.0 !!

**Comment by yngwiechou** [comment]
Have an issue with:

/var/log/xlxd.xml

Empty content will be generated every 15 seconds.

Regards,
Yngwie
BU2EA

**Comment by yngwiechou** [comment]
It seems xlxd failed to GetPeers() and broke the WriteXmlFile()


xmlFile << "<" << m_Callsign << "linked peers>" << std::endl;

<----------- WriteXmlFile break here before GetPeers()
// lock
CPeers *peers = GetPeers();
// iterate on peers
for ( int i = 0; i < peers->GetSize(); i++ )
{
	peers->GetPeer(i)->WriteXml(xmlFile);
}

**Comment by iz7jwr** [comment]
I can not connect MMDVM. With the parameters of my XLX023 into MMDVM.ini. The contents of the Log / var / log / messages file are:
"Aug 23 05:17:59 v12356 xlxd: DMRmmdvm connect packet from unrecognized id 2227145"
"Aug 23 05:17:59 v12356 xlxd: DMRmmdvm packet (8)"

**Comment by yngwiechou** [comment]
Ok, the issue was caused by a flapping peer.

After removing the problematic interlink peer, GetPeers() works well.

But improvement in GetPeers() is still needed in handling the case with unstable interlinks.

Regards,
Yngwie
BU2EA

**Comment by phl0** [comment]
You need to have a valid dmrids.dat file containing the DMR IDs and callsigns.

**Comment by yngwiechou** [comment]
main.h:#define DMRIDDB_PATH                    "/xlxd/dmrid.dat”

**Comment by phl0** [comment]
And #define DMRIDDB_USE_RLX_SERVER should be set to 1 or otherwise create that file manually.

**Comment by yngwiechou** [comment]
Use the command below to generate the dmrid.dat

/xlxd# wget -O dmrid.dat http://xlxapi.rlx.lu/api/exportdmr.php

**Comment by LX1IQ** [comment]
Hi guys,

I updated the install doc in the group a few minutes ago.
Please have a look.

73, Luc

**Comment by LX1IQ** [comment]
Please read the installation doc in the yahoo group ! You need a valid dmrid.dat in the xlxd/ folder.
I will update the readme in the next days.

73, Luc
