### ISSUE TITLE
Dont Start

### ISSUE THREAD

**Issue by ameyst** [LX3JL/xlxd#64]
308/5000
Hello,
I have done the installation with the readme
nothing appears in the process list and the xlxd.xml is not created.

root @ s265269: ~ # service xlxd start
Starting xlxd:
root @ s265269: ~ #

the server is a V-Server with Debian 7.11 64bit

I have no idea what's wrong

greetings stefan

**Comment by phl0** [comment]
What is the output if you start the process by hand?

**Comment by ameyst** [comment]
nothing and the pit is empty

**Comment by phl0** [comment]
Screenshot please

**Comment by ameyst** [comment]
root@s265269:~# cd /xlxd/               
root@s265269:/xlxd# ./xlxd --chuid root:root  -- XLX263 78.46.11.69
root@s265269:/xlxd# ./xlxd --chuid root:root --XLX263 78.46.11.69
root@s265269:/xlxd# /etc/init.d/xlxd start                       
Starting xlxd: 
root@s265269:/xlxd#

**Comment by phl0** [comment]
You need to add the ip address of the transcoder. If it is not present try 127.0.0.1 instead.
Also the chuid stuff does not make sense to me. Just try "xlxd XLX263 78.46.11.69 127.0.0.1".

**Comment by LX1IQ** [comment]
I guess we can close this issue.

73, Luc
