### ISSUE TITLE
reloading dmrid.dat

### ISSUE THREAD

**Issue by stefansaraev** [LX3JL/xlxd#68]
Hi,

I've noticed that dmrid.dat was never re-loaded, it seems that it is required to restart xlxd in order to accept connections via mmdvm protocol from clients that were not defined in dmrid.dat previously

http://paste.debian.net/1000930/ is a quick and dirty hack that works for me. it would be nice if reloading of dmrid.dat can be implemented properly.

**Comment by stefansaraev** [comment]
implemented in 32a437c. thanks.

**Comment by LX1IQ** [comment]
You're welcome.
73, Luc
