### ISSUE TITLE
Repeaters are sorted in the first column of Modules table in users.php

### ISSUE THREAD

**Issue by yngwiechou** [LX3JL/xlxd#7]
This issue applies to dashboard2 only.

I believe that the "Modules" table in users.php is intended to list user's nodes belong to the module under its column.

For example: Assuming there are two Modules in use, Node 1 & 2 is connected to Module A, while Node 3 on Module B

```
Module A   Module B
-------------------------
Node 1       Node 3
Node 2
```

However, the current code will display all the users, in the first column like this.

```
Module A   Module B
-------------------------
Node 1       
Node 2
Node 3
```

I managed to fixed the issue with the following change, please take look to see if it is appropriate.
Thanks!

Regards,
Yngwie Chou

```
=================================================

$ diff -u users.php users.php.fixed
--- users.php	2016-07-15 20:18:25.000000000 +0800
+++ users.php.fixed	2016-07-16 00:03:48.000000000 +0800
@@ -70,26 +70,39 @@

 echo '</tr>';

+$ModuleUsers = array();
 for ($i=0;$i<count($Modules);$i++) {
-
-    $Users = $Reflector->GetCallSignsInModules($Modules[$i]);
-
-   $UserCheckedArray = array();
-
-   for ($j=0;$j<count($Users);$j++) {
-      if (in_array($Users[$j], $UserCheckedArray)) {
-         $CurrentPositions = array_keys($UserCheckedArray,$Users[$j]);
-         $Displayname = $Users[$j].'-'.$Reflector->GetSuffixOfRepeater($Users[$j], $Modules[$i], max($CurrentPositions)+1);
-      }
-      else {
-         $Displayname = $Users[$j].'-'.$Reflector->GetSuffixOfRepeater($Users[$j], $Modules[$i]);
-      }
-      echo '
-            <tr>
-               <td><a href="http://www.aprs.fi/'.$Displayname.'" class="pl" target="_blank">'.$Displayname.'</a> </td>
-            </tr>';
-      $UserCheckedArray[] = $Users[$j];
-   }
+	$Users = $Reflector->GetCallSignsInModules($Modules[$i]);
+	$ModuleUsers[$i] = $Users;
+}
+
+// Find the max node count per module
+$MaxNodeRows = 0;
+foreach ($ModuleUsers as $mUsers) {
+	if ($MaxNodeRows < count ($mUsers)) {
+		$MaxNodeRows = count ($mUsers);
+	}
+}
+
+for ($k=0;$k<$MaxNodeRows;$k++) {
+	echo '<tr>';
+	for ($i=0;$i<count($Modules);$i++) {
+		$UserCheckedArray = array();
+		if ($ModuleUsers[$i][$k]) {
+			if (in_array($ModuleUsers[$i][$k], $UserCheckedArray)) {
+				$CurrentPositions = array_keys($UserCheckedArray,$ModuleUsers[$i][$k]);
+				$Displayname = $ModuleUsers[$i][$k].'-'.$Reflector->GetSuffixOfRepeater($ModuleUsers[$i][$k], $Modules[$i], max($CurrentPositions)+1);
+			}
+			else {
+				$Displayname = $ModuleUsers[$i][$k].'-'.$Reflector->GetSuffixOfRepeater($ModuleUsers[$i][$k], $Modules[$i]);
+			}
+			echo '<td><a href="http://www.aprs.fi/'. $Displayname .'" class="pl" target="_blank">' . $Displayname . '</a></td>';
+			$UserCheckedArray[] = $ModuleUsers[$i][$k];
+		} else {
+			echo '<td></td>';
+		}
+	}
+	echo '</tr>';
 }

 ?>
================================================================

```

**Comment by yngwiechou** [comment]
After checking dashboard (1) cods, here a better fix for the issue.

However, I don't know how to shift the table-striped by 1, hence I used non-striped class for the enclosed table in the module <td>

73,
Yngwie
Bx2AFC

```
$ diff users.php users_fix2.php
54c54
<       <table class="table table-striped table-hover">
---
>       <table class="table table-striped">
72a73,74
> echo '<tr>';
>
75a78,81
>     echo '
>    <td valign="top" style="border:0px;padding:0px;">
>
>       <table class="table table-hover">';
88c94
<             <tr>
---
>       		<tr>
92a99,102
>    echo '
>       </table>
>
>    </td>';
94a105,106
> echo '</tr>';
>
```

**Comment by lamaral** [comment]
Hi yngwiechou, sorry for the delay in the answer. I was out of reach this week.

Do you have this dashboard in use in a XLX server? I'm part of the XLX724 team and we only have users on Module B, so I have no way to test those changes.

I have some work that need to be done by tomorrow. I can take a look carefully on Monday.

**Comment by phl0** [comment]
Luiz,

I can do tests if you like. I have various repeaters that can be linked to all modules on my XLX. Also some clients linke MMDVM, UP4DAR, DVmega...

   vy73 de Florian DF2ET

**Comment by lamaral** [comment]
Hi Florian,

That would be really helpful. 

TY, 73

**Comment by lamaral** [comment]
Hi Florian and Yngwie,

I made some changes to the code that I believe would fix that problem. Please try the code in my repo https://github.com/lamaral/xlxd to see if it fixes that problem.

Thank you.

**Comment by phl0** [comment]
Luiz,

the fix works fine. This is what the current state in LX3JL repo looks like:
![screenshot from 2016-07-16 21 51 23](https://cloud.githubusercontent.com/assets/7112907/16896838/f877cad8-4b9f-11e6-9cc2-abfa7f6f9e94.png)


And this is the result from the test with your branch:
![screenshot from 2016-07-16 21 52 13](https://cloud.githubusercontent.com/assets/7112907/16896839/fda9baa2-4b9f-11e6-82f4-5f80bd4e15bb.png)

In both cases DB0BS-B was linked to my XLX module B. So the code was buggy and your fix is good. I think you can put it into a PR for the LX3JL repo.

   vy73 de Florian DF2ET

**Comment by yngwiechou** [comment]
Hi Luiz,

The fix is works fine.


But if you can take a look my proposed fix #2, the presentation on web will be a little bit better



Thanks a lot.

Regards,
Yngwie

**Comment by yngwiechou** [comment]
Hi Luiz,

Here my fix.

https://github.com/yngwiechou/xlxd

Please help to take a look to see if it is better.

Regards,
Yngwie

**Comment by lamaral** [comment]
I believe this issue can be closed, as a fix was provided in the pull request #9.

**Comment by lx1iq** [comment]
Hi guy's, Jean-Luc will close the issue when he is back from holidays.
Good work !

**Comment by phl0** [comment]
@yngwiechou could close this issue as well as he was the author of this issue ;-)

**Comment by lx1iq** [comment]
Of course :-)
