### ISSUE TITLE
Request: pass connection option on XLX interlink to force DMR to D-STAR transcoding

### ISSUE THREAD

**Issue by cyanide-burnout** [LX3JL/xlxd#74]
Existing version of XLX Interlink has requirement to pass D-STAR and DMR traffic at the same time.
Interlink can be forced to do D-STAR to DMR transcoding by downgrading version number.
Please add capability to force DMR to D-STAR conversion.

**Comment by cyanide-burnout** [comment]
My existing idea is to reuse revision number to pass something like PROTOCOL_VERSION_2_SPECIAL to force DMR to D-STAR transcoding. For example I can use revisions > 200 to force that.
If you OK with this approach I can prepare pull request.

**Comment by stefansaraev** [comment]
@cyanide-burnout @LX3JL c3920519872deb15cf7afc3673221d0541085cdf works for me. thanks guys.

**Comment by LX1IQ** [comment]
Hi,
Tnx for the feedback. I guess Artem can close this one.

73,  Luc
