### ISSUE TITLE
Feature request: Define the Module which has to be transcoded

### ISSUE THREAD

**Issue by oe5stm** [LX3JL/xlxd#77]
Hi Luc,

i think that it is important for the future to have the possibility to choose the Module which is been transcoded.
Every stream right now is send to the AMBE-Server and so i get stuck with only 4 Channels available.

Bye
Timm

**Comment by ik5xmk** [comment]
The strength of a reflector like XLX is the possibility of having separate modules. But it is important to think in the future (not too remote, hope) to a flexible management of the same. Then define (as I authorize a peer) on which module transcoding is present and which protocols are active. As the interlink file is present, there should be a file in which to manage the configuration of the modules. Thanks, 73. David IK5XMK

**Comment by iw2gob** [comment]
Hi all,  
I believe that the possibility of choosing the module that needs to be transcoded is fundamental and can even heavily influence the future of the XLX multi-protocol system. Some XLX networks in the world have different needs and the flexibility of the configuration is a very important aspect that should not be underestimated.
I hope Luc can soon change his point of view on this issue.

73, Maurizio IW2GOB

**Comment by oe1kbc** [comment]
Hi,
i found a quick solution:

change source cpacketstream.cpp

bool CPacketStream::Open(const CDvHeaderPacket &DvHeader, CClient *client)
{
    bool ok = false;
   
    // not already open?
    if ( !m_bOpen )
    {
        // update status
        m_bOpen = true;
        m_uiStreamId = DvHeader.GetStreamId();
        m_uiPacketCntr = 0;
        m_DvHeader = DvHeader;
        m_OwnerClient = client;
        m_LastPacketTime.Now();
		if(DvHeader.GetRpt2Module() == 'A' || DvHeader.GetRpt2Module() == 'M')
			m_CodecStream = g_Transcoder.GetStream(this, client->GetCodec());
		else
			m_CodecStream = g_Transcoder.GetStream(this, CODEC_NONE);
        ok = true;
    }
    return ok;
}

73 de Kurt
OE1KBC

**Comment by IZ7AUH** [comment]
Kurt,
many tnx I put your code into my XLX099 on module U and now a Trasconde is locked yo U only...

**Comment by stefansaraev** [comment]
there is a quick working solution in my git.

**Comment by vk4tux** [comment]
Thankyou Stefan You have some good code there ;
root@XLX389:~# git clone https://github.com/stefansaraev/xlxd.git xlxd_stefan
Cloning into 'xlxd_stefan'...

**Comment by ik5xmk** [comment]
Thank you very much to all, hoping that Luc can implement these changes with activation, perhaps, from the command line or similar, in the next version. 73, David

**Comment by citynetcomputing** [comment]
Ditto!
