### ISSUE TITLE
XLX server not listed ? 

### ISSUE THREAD

**Issue by Noerbom** [LX3JL/xlxd#81]
Hi Luc.

I have just created a xlx server for Denmark. XLX238. But its still not listed in the reflector list. Can you please add it ? 

thanks 

73 - Lasse oz6nor.

**Comment by Noerbom** [comment]
Link to server : http://xlx238.brandmeister.digital

**Comment by phl0** [comment]
Did you activate the callinghome function in the dashboard config?

**Comment by Noerbom** [comment]
It did the trick.. Thanks :)

**Comment by LX1IQ** [comment]
HI Noerbom,
So I believe we can close this case ?

73, Luc

**Comment by Noerbom** [comment]
Hi Luc...:-)

yes problem is solved :-)
73 - OZ6NOR - Lasse

2018-02-18 18:17 GMT+01:00 LX1IQ <notifications@github.com>:
