### ISSUE TITLE
Stacking 3006's

### ISSUE THREAD

**Issue by vk4tux** [LX3JL/xlxd#93]
When trying to combine two 3006 units i get ;

"FTDI function FT_OpenEx error 3"

on 2nd unit. They work ok individually.

Starting AMBEd 1.3.1

Initializing vocodecs:
Detected 4 USB-FTDI devices

Description : USB-3006 A         Serial : FT2JNR9HA
Description : USB-3006 B         Serial : FT2JNR9HB
Description : USB-3006 A         Serial : FT34XXDKA
Description : USB-3006 B         Serial : FT34XXDKB
Opening USB-3006_A:FT2JNR9HA device
ReadDeviceVersion : 0AMBE3003F1V120.E100.XXXX.C106.G514.R008.A0030608.C0020208/

Opening USB-3006_B:FT2JNR9HA device
ReadDeviceVersion : 0AMBE3003F1V120.E100.XXXX.C106.G514.R008.A0030608.C0020208/

Opening USB-3006_A:FT34XXDKA device
FTDI function FT_OpenEx error 3

Codec interfaces initialized successfully : 6 channels available

Initializing controller

**Comment by vk4tux** [comment]
cftdidevicedescr.cpp | 2018-Jun-22 12:43:52 | 26.0K | text/x-c++src
-- | -- | -- | --
cftdidevicedescr.h | 2018-Jun-22 13:13:49 | 3.5K | text/x-chdr

**Comment by ea5gvk** [comment]
Hi Adrian, Please I have some problem.
When trying to combine two BAOFARM units i get ;

"FTDI function FT_OpenEx error 3"

on 2nd unit. They work ok individually.
Please help me. I thx.
