### ISSUE TITLE
How to distinguish a DMR vs DStar key up

### ISSUE THREAD

**Issue by sixfootseven** [LX3JL/xlxd#95]
I am trying to have a live display on our dashboard of whether the current talker is using DMR or DStar, and I can't find a reliable method. I can't use the callsign of their repeater or gateway, as some users have the same callsign and band for 2 different connections - DMR and DStar. Can the syslog entries please have the mode somewhere in the entry? Or is there another way to tell? 

Jul  1 20:58:15 xlx xlxd: Opening stream on module A for client ZL2EZ  B with sid 3150

**Comment by vk4tux** [comment]
The suffix box indicates a suffix entry for the dstar user and no suffix
for the dmr user.


-----Original Message-----

**Comment by sixfootseven** [comment]
Cheers, figured i might have missed something obvious. Thanks Adrian.

**Comment by vk4tux** [comment]
If 'DMR' is seen in the suffix field, it indicates a BM TG source via
XLX Interlink.

-----Original Message-----
