### ISSUE TITLE
Request: Parrot / Echofunction

### ISSUE THREAD

**Issue by sm0tsc** [LX3JL/xlxd#96]
It would be nice with a parrot / echo function for testing

//TSC

**Comment by narspt** [comment]
+1

**Comment by LX1IQ** [comment]
Hi,

This was already discussed a few times. We are not going to sacrifice a module for a parrot.

73, Luc

**Comment by narspt** [comment]
Hard coded always enabled on a specific module I would 100% agree with you Luc, but as an option (main.h) allowing it to enable if wished on some module... I don't see why not... and I also think it would be great for testing purposes, but just my humble opinion...

**Comment by narspt** [comment]
https://github.com/narspt/XLXEcho
